package ar.edu.itba.pod.agent.runner;

/**
 * Event that is targetted to a specific agent
 * Events implementing this interface provide information that may be used by the simulation 
 * engine to optimize the traffic generated by events that are meant to one recipient as opposed to 
 * multicast events.
 */
public interface TargetedEvent {
	/**
	 * Returns the specific target for this event.
	 */
	public String target();
}
